### ISSUE TITLE
Testcase grok'ing with kyua list/kyua test breaks if something prints to stderr in atf_init_test_cases

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#149]
I am integrating lib/libarchive/tests into the FreeBSD test suite and discovered that the "Unrecognized option" message printed to the stderr was breaking atf_init_test_cases for kyua list and kyua test.

Once I redirected stderr to stdout, the test script became functional with kyua list/kyua test.

Something like this should repro the issue:

<pre>
atf_test_case a
a_body() {
    true
}
atf_init_test_cases()
{
    echo "hello world" >&2
    atf_add_test_case a
}
</pre>

**Comment by jmmv** [comment]
You cannot do anything in `atf_init_test_cases` other than register test programs. In particular, printing stuff to stdout/stderr is going to mess things up, because it's going to collide with the output of the test cases listing retrieved via `-l`. That's how the interface of ATF test programs is defined.
