### ISSUE TITLE
Add gdb configuration variable for kyua.conf

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#165]
Since kyua is configured on the FreeBSD package cluster and the poudriere instance has /usr/bin/gdb installed, the kyua package gets configured to look for gdb in /usr/bin/gdb .

This means that if someone installs the package, removes /usr/bin/gdb, then runs a test which crashes, it will fail to execute gdb after the fact.

kyua.conf should have a knob for specifying which copy of gdb to use so end-users could specify a different path from the base system copy of gdb.

**Comment by jmmv** [comment]
If you configure Kyua with:

`./configure GDB=gdb`

i.e. with a bare name in the `GDB` variable instead of a full path, Kyua should look up `gdb` at run time based on the `PATH`. I think this addresses your issue, so I'm closing it (but reopen it if not).

What should be done, then, is changing the FreeBSD port to support the above somehow...
